# fly.toml app configuration file generated for phonebook-divine-sky-7392 on 2025-09-03T00:49:44+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'edwardphonebook'
primary_region = 'cdg'

[build]

[env]
PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
